# Generated by Django 3.2.16 on 2023-02-18 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vblog', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='category',
        ),
        migrations.AddField(
            model_name='viewcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viewcount',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vblog.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='ip_user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
