# Generated by Django 3.2.16 on 2023-02-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vblog', '0005_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carousel',
            field=models.BooleanField(default=True),
        ),
    ]
