# Generated by Django 3.2.16 on 2023-02-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vblog', '0006_post_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='post',
            name='url_imagen',
            field=models.CharField(default='bafybeiff234nianjb5dxthct7x6frafnisl4ne3zisgfmcmu4cl7mfv42y', max_length=900, null=True),
        ),
    ]
